### ISSUE TITLE
Does this work with Fathom Pro?

### ISSUE THREAD

**Issue by brandondeweese** [stenvdb/craft-fathom-analytics#1]
I have a pro account and I'm getting no data to populate on any of my site's dashboards.

**Comment by stenvdb** [comment]
No, sorry. It's mentioned in the docs (https://github.com/stenvdb/craft-fathom-analytics/#fathom-analytics-overview).

It's because Fathom currently has no official API. I've started work on this to support Fathom Lite, and work with the internal (undocumented) API at the moment. But Fathom has announced it will start work on an official API for their pro plans: https://twitter.com/usefathom/status/1226859803529510912

Once it's out, I will start start implementing support for it in this plugin.

**Comment by daveyjones** [comment]
Looking forward to using this with our pro account!

**Comment by stenvdb** [comment]
@daveyjones It is definitely on the agenda once it's out. I've read maybe in April.. 🤞
